### ISSUE TITLE
主题摘要标签的问题。

### ISSUE THREAD

**Issue by aaron-codes** [A-limon/pacman#1]
不知道是不是我设置的问题，使用标签显示摘要，不起作用。使用其他主题是正常的。

**Comment by A-limon** [comment]
因为设计的时候希望首页文章不显示图片，但是实现起来比较复杂，只能手动选择摘要。如果使用可能截断的文章中包含图片。所以，请在md文件中使用description声明摘要。该摘要会被显示到首页。
