### ISSUE TITLE
我使用了你的主题，但有个问题不是很明白

### ISSUE THREAD

**Issue by mlosun** [A-limon/pacman#10]
在使用多说的评论那里，为什么只需要设置short_name
而不需要填写多说的密钥

这样会不会造成short_name公开了评论混乱的情况？

**Comment by A-limon** [comment]
完全不必担心，多说是根据这个short_name来保证此处评论框是你的，此外他还会根据文章地址URL进行进一步匹配，你去多说的网站生成的代码也同样。没人会无聊的用你的short_name~ 请放心使用。

**Comment by mlosun** [comment]
多谢解答，明白了~
