### ISSUE TITLE
斜体会处理为粗体

### ISSUE THREAD

**Issue by PhiloSky** [A-limon/pacman#14]
`*斜体*`会显示为`**粗体**`
应该是这样的
_斜体_ **粗体**
jacman，landscape等主题无此问题
我是小白，不会改，就提交下问题吧:-)

**Comment by A-limon** [comment]
请问下这个问题已会出现在正文中还是标题里？

**Comment by PhiloSky** [comment]
正文里，标题没试过

**Comment by A-limon** [comment]
Thank you for your commit.
