### ISSUE TITLE
2013-12-22master分支版本的页面显示问题

### ISSUE THREAD

**Issue by jeromesun14** [A-limon/pacman#2]
我直接git clone到themes目录下，并没有做任何修改。发现有如下问题：
1. h1没有缩进，没有像h2、h3那样特殊处理；
2. 表格没有缩进，表格默认没有画边框；
3. 有序列表默认没有缩进，且列表的编号未显示出来。
4. code会显示两行行号

效果图：  
![pacman](https://f.cloud.github.com/assets/5097261/1801194/5b4f7760-6be1-11e3-868c-fcab3dfca0cf.png)

以上问题在light主题都不会出现。  
我的版本信息：

```
sunnogo@a3e420:~/github/hexo$ hexo version
hexo: 2.3.0
os: Linux 3.8.0-34-generic linux ia32
http_parser: 1.0
node: 0.11.10-pre
v8: 3.22.24.5
uv: 0.11.15
zlib: 1.2.3
modules: 13
openssl: 1.0.
```

PS：我是一个对前端一点都不了解的嵌入式码农，超喜欢这个主题，但是却不知道改哪。很期待您的回复。

**Comment by A-limon** [comment]
您好，感谢支持
1，h1在文章页面会有0.5em的缩进，回合左边橙色的竖线保持一点距离
2，3和有序列表和表格在这一版本中还没进行处理，近期我正在开发第二版，会考虑表格问题。
4，不介意的话可以告诉我您的博客地址，看看为什么会显示两行主题。
因为这个主题也是我第一次做的主题，比起官方的主题有很多欠缺的地方，我会继续改进，谢谢！

**Comment by jeromesun14** [comment]
1，关注h1的原因是之前一直把h1当标题（title）使，最近发现pandoc中，h1就是一级标题，title有title的语法。而我之前却是将h1当成title，h2当成一级标题。
4，code会显示两行行号，这个问题突然想到原因了：默认的`_config.yml`中有如下选项，我之前的默认是把`line_number`置成true了，把true去掉后OK。

```
 highlight:
   enable: true
   line_number:
   tab_replace:
```

不过我个人建议把主题内部的自动加行号去掉，不然会造成理解上的不统一。
