### ISSUE TITLE
hexo构建失败

### ISSUE THREAD

**Issue by dukewan** [A-limon/pacman#21]
使用hexo构建失败了。报错如下：
![qq20140716-2 2x](https://cloud.githubusercontent.com/assets/2100515/3594360/e2a1db68-0c9a-11e4-8514-eeb44d68aa34.png)

可能是主题的问题，换成官方的主题就不会失败了。

**Comment by A-limon** [comment]
请先检查下主题和hexo的配置文件，里面是否有空的

**Comment by dukewan** [comment]
检查了一边，不是空的。然后我又用hexo新建了一个blog，clone了pacman，修改了_config.yml中theme配之后，是同样的报错。

**Comment by Aixile** [comment]
https://github.com/hexojs/hexo/issues/722

**Comment by Xuanwo** [comment]
正如我之前开的issuehttps://github.com/hexojs/hexo/issues/722所言，最新版本的hexo有关策略修改了，要把主题里的languages中的achieve_b加上引号

**Comment by dukewan** [comment]
Edit all of the yml file in the language folders  of thirdparty theme , add quotation marks when there is a space between the values. 
![qq20140718-2 2x](https://cloud.githubusercontent.com/assets/2100515/3622133/2b419004-0e29-11e4-8977-a663954d8986.png)
