### ISSUE TITLE
请问是如何在 http://yangjian.me/ 下生成子博客 http://yangjian.me/pacman

### ISSUE THREAD

**Issue by wuchong** [A-limon/pacman#37]
您好，我看到您的博客根目录下有个为 Pacman 架设的demo，http://yangjian.me/pacman

但是我看了您博客的源码https://github.com/A-limon/a-limon.github.com，并没有找到有为pacman专建的文件。请问您是如何实现http://yangjian.me/pacman的？

**Comment by A-limon** [comment]
你只要在github绑定了域名，你其他项目的站点就会自动的成为子站点。

**Comment by wuchong** [comment]
多谢，还有一个小问题，如何在图片下面加上图片说明呀，就像下面这样。
![image](https://cloud.githubusercontent.com/assets/5378924/5081693/3f168e22-6f0e-11e4-9734-248f163f49a0.png)

看到在HTML源码中是多了这一句，`<span class="caption">Small Picture</span>`，在markdown中应该用什么语法写的呢？
