### ISSUE TITLE
怎样把归档中的列表修改成一行一行的

### ISSUE THREAD

**Issue by cuckootan** [A-limon/pacman#41]
rt

另外，能不能在文章页面中加上  返回开头 的小插件啊

主题很精美！很赞！希望能更好～

谢谢！

**Comment by Andrew-liu** [comment]
返回顶部可以通过js计算页面差来实现, 当超过每个页面高度后, 按钮出现, 点击按钮触发点击事件动画式返回顶部, 另外归档列表就是一行一行吧
