### ISSUE TITLE
文章content连接有点问题

### ISSUE THREAD

**Issue by Ming-Zhe** [A-limon/pacman#6]
如题。。。我这测试的有点问题。

**Comment by A-limon** [comment]
提供下截图或者代码。

**Comment by Ming-Zhe** [comment]
![](https://farm8.staticflickr.com/7425/13106286385_405e67b257_o.png)

就是点文章中的这个content里的链接，不能正确跳转到相应的段落。

**Comment by A-limon** [comment]
这个我在介绍主题的文章中说明了这个问题：这目前是hexo目录功能的bug，只支持英文开头的。相信以后会更新的。

**Comment by Ming-Zhe** [comment]
这样啊。。。我没注意。知道了
